// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qzlpfhbhnnpzmuwgkrbf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF6bHBmaGJobm5wem11d2drcmJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzExNzE5NzEsImV4cCI6MjA4Njc0Nzk3MX0.n_AG5MpUoLMIJ6jBkYW5xRc4JEENVFar8kCJJ_ycfwU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});